version: '3.8'
services:
  web:
    build: .
    image: ibkr-rest-api
    container_name: ibkr
    environment:
      IBKR_ACCOUNT_ID: "DUO504961"
    ports:
      - "5055:5055"
      - "5056:5056"
      - "4002:4002"
    volumes:
      - ./webapp:/app/webapp
      - ./ibkr-algo-tradeapp:/app/ibkr-algo-tradeapp
